apiVersion: v1
kind: Service
metadata:
  name: goapi-service
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - protocol: TCP
      name: http-svc
      port: 80
      targetPort: 3000
